MunifTanjim/nui.nvim

lua/nui/popup/init.lua

fix(popup): respect 'enter' option on subsequent mounts

---

lua/nui/popup/border.lua
lua/nui/popup/init.lua

supports popup:set_position(...) when unmounted or mounted
Also supports:
position (required. same as popup_options.position)
relative (optional, same as popup_options.relative, unchanged if not provided)
Let me know what you would change :D
Also, I think `set_size()` popup method needs this change:
```lua
if self.border.win_config then
self.border:resize()
end
```
Because when using this in config to initialize popup():
```
border = {
style = "none",
}
```
makes `set_size()` error. `attempt to index field 'win_config' (a nil value)`

Add popup:set_position(position, relative)

---

lua/nui/input.lua

If `Input` is closed from insert mode, `:stopinsert` after unmount.
resolves #34

fix(input): stopinsert on close

---

lua/nui/popup/init.lua

This PR adds `hide` and `show` methods to the `Popup` component.
I was embedding Neovim's `terminal` into a Popup and unmounting the component it deletes the `buf` also, which makes it impossible to toggle the popup.

feature: add hide and show methods

---

lua/nui/line/README.md
lua/nui/line/init.lua
lua/nui/text/README.md
lua/nui/text/init.lua
lua/nui/utils/init.lua
tests/nui/line/init_spec.lua
tests/nui/text/init_spec.lua

make ns_id required, update method signature 
makes ns_id required for :highlight, :render, :render_char methods.
if -1 is provided, a fallback ns_id will be used.
BREAKING CHANGE: change parameter order for methods.
---
Better do this now, sooner than later. Explicitly using namespace with extmarks is preferred.

Feat make ns id required

---

lua/nui/menu/README.md
lua/nui/menu/init.lua
tests/nui/menu/init_spec.lua

Use case:
```lua
on_change = function(item, menu)
local progress = 0
local pos = nil
for i, val in pairs(menu_items) do
if val == item then
pos = i
end
end
progress = math.floor((pos / #menu_items) * 100)
menu.border:set_text('bottom', tostring(progress), 'right')
end,
```
Not really sure if you would have preferred the reference to menu attached to the node rather than passed as a parameter but I think is pretty nice. Confirmed working as well.
Let me know what you think about this! 😄

feat(menu): pass reference of menu to on_change event

---

lua/nui/popup/README.md
lua/nui/popup/border.lua
lua/nui/popup/init.lua
lua/nui/utils/init.lua
lua/tests/nui/init.lua
tests/nui/popup/border_spec.lua
tests/nui/popup/init_spec.lua

`:set_layout` replaces the following methods:
- `:set_position`
- `:set_size`

feat(popup): add method popup:set_layout(config)

---

lua/nui/tree/README.md
lua/nui/tree/init.lua
tests/nui/tree/init_spec.lua

nui blocks should not have anything to do with windows. They will only deal with the buffer.

feat(tree): add o.bufnr and deprecate o.winid

---

lua/nui/text/init.lua
tests/nui/text/init_spec.lua

For cloning a text with new highlight group:
```lua
local new_text = Text(old_text, new_hl)
```
When `new_text` is rendered, it will create a new extmark.
---
For updating highlight group for existing text:
```lua
text:set(text:content(), new_hl)
```
When `text` is rendered the next time, if it previously had highlight, the same extmark will be updated and used.

feat(text): improve extmark handling

---

lua/nui/popup/init.lua

This fixes a bug discovered in a Neo-tree test: 
```
Fail    ||      Filesystem reveal command should toggle the reveal-state of the floating window
.../neo-tree/sources/filesystem/filesystem_command_spec.lua:9: Vim(lua):E5108: Error executing lua ...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:
121: Invalid buffer id: 11
stack traceback:
[C]: in function 'nvim_buf_clear_namespace'
...m/site/pack/packer/start/nui.nvim/lua/nui/utils/init.lua:121: in function 'clear_namespace'
...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:247: in function '_buf_destory'
...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:272: in function 'unmount'
...eickel/repos/neo-tree.nvim//lua/neo-tree/ui/renderer.lua:141: in function 'close_floating_window' …
```

Fix `invalid buffer id` in Neo-tree test

---

lua/nui/popup/border.lua

Currently `noautocmd` is not set (like for the popup window) when opening the border.
This leads to issue with other floats like Telescope.
Fixes Noice issue https://github.com/folke/noice.nvim/issues/11

fix: set noautocmd before opening border window

---

lua/nui/popup/border.lua
lua/nui/popup/init.lua

Hi!
The `anchor` window option did not exist yet, so I added it.
If there's a border, the popup is anchored to the deafult anchor `NW`. And the border is anchored to the popup `anchor`.
If there's no border, the popup window itself sets the `anchor`.
This should cover all cases I think

feat: added support for `anchor`

---

lua/nui/popup/border.lua
tests/nui/popup/border_spec.lua

Highlight complex border characters explicitly as `FloatBorder`.
Complex border's `Normal` should be the same as the actual popup's `Normal`.

fix(popup): properly apply winhighlight

---

lua/nui/popup/border.lua

Some Noice users like to do `%bw` to wipe all buffers (which they shouldn't do, but anyway). This leads to issues in Noice, Nui and Notify.
I've just fixed them all in each project.
Fixes:

fix(popup): check if border bufr is valid before clearing namespace

---

lua/nui/popup/border.lua
tests/nui/popup/border_spec.lua

Match the default behavior of Neovim.
References:
> https://github.com/neovim/neovim/blob/92005db76039094d4a7180c1398b43c06940a1a1/runtime/doc/api.txt#L457
> - |hl-FloatTitle| for window's title
> https://github.com/neovim/neovim/blob/92005db76039094d4a7180c1398b43c06940a1a1/runtime/doc/api.txt#L3094-L3096
> default highlight group is `FloatTitle`

feat(popup): default border.text hl to FloatTitle

---

lua/nui/popup/init.lua

Resolves https://github.com/MunifTanjim/nui.nvim/issues/250
---
patch for upstream issue:
- https://github.com/neovim/neovim/issues/20370

fix(popup): do not reset win_options on update_layout call

---

lua/nui/input/init.lua

Resolves: https://github.com/MunifTanjim/nui.nvim/issues/257

fix(input): escape multi-byte chars in default value

---

lua/nui/popup/border.lua

When creating a popup on a nonmodifiable buffer, creating the border fails, probably becasue it inherits the nonmodifable option.
Fixes https://github.com/folke/noice.nvim/issues/567

fix(popup): make sure border buf is modifiable

---

lua/nui/menu/init.lua
tests/nui/menu/init_spec.lua

This PR resolves the following:
1. LuaLS warning: ```Missing required fields in type `nui_popup_internal`: `position`, `size`.```
2. Error when opening a Menu in a Layout without the `size` field.
Very new to the project so please let me know if there are specific unit tests I should update/add!
Error:
```
Error executing Lua callback: ...er/.local/share/nvim/lazy/nui.nvim/lua/nui/menu/init.lua:80: attempt to index field 'size' (a nil value)
stack traceback:
...er/.local/share/nvim/lazy/nui.nvim/lua/nui/menu/init.lua:80: in function 'make_default_prepare_node'
...er/.local/share/nvim/lazy/nui.nvim/lua/nui/menu/init.lua:286: in function 'init'
.../.local/share/nvim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function 'Menu'
...uments/griptape/griptape.nvim/lua/griptape/structure.lua:19: …
```

Add Missing Internal Fields

---

tests/nui/layout/init_spec.lua
tests/nui/popup/border_spec.lua
tests/nui/popup/init_spec.lua

`vim.api.nvim_win_get_config` used to return a dict of numbers to represent a vim float number for `row` and `col` fields. This behavior was fixed in https://github.com/neovim/neovim/pull/27284 as a **breaking change** to the old API without any notice. Now user can refer to the value of `config.row` without indexing like `config.row[vim.val_idx]`.
This is the reason why tests are failing in https://github.com/MunifTanjim/nui.nvim/pull/332.

fix(ci): fix tests using old nvim api

---

lua/nui/split/init.lua

reference: https://github.com/MunifTanjim/nui.nvim/pull/197
The exact same thing (multiple hidden splits point to the same bufnr) can happen to `NuiSplit` as well.
I get the error message: _`Invalid 'group': 'nui_<id>_hide'`_ when I try to `split:show()`.
Hope this gets merged as soon as possible :)
Thanks in advance.
---
```txt
  Error  Error executing vim.schedule lua callback: /path/to/nui/split/init.lua:180: BufWinEnter Autocommands for "<buffer=10>": Vim(append):Error executing lua callback: /path/to/nui/split/init.lua:240: Invalid 'group': 'nui_2_hide'
stack traceback:
[C]: in function 'create'
/path/to/nui/split/init.lua:240: in function </path/to/nui/split/init.lua:234>
[C]: in function 'nvim_win_set_buf'
/path/to/nui/split/init.lua:180: in function '_open_window' …
```

fix(split): manual doautocmd BufWinEnter for splits

---

lua/nui/split/init.lua
tests/nui/split/init_spec.lua

https://github.com/MunifTanjim/nui.nvim/discussions/335
> [!WARNING]
> 
> I haven't added any tests and I don't know how to work with the test suite.
> It would be nice if you @MunifTanjim could make a followup PR if you want to add some tests.

fix(split): always spawn split from current window when relative = editor

---

lua/nui/layout/utils.lua

Fixes https://github.com/folke/noice.nvim/issues/636.
There are many ways to fix this issue, but I think my approach is the cleanest.
Other options:
- Overwrite `internal.position.win` to nil just like `win_config.win` here. (`win_config.win` will be nil, but `internal.position.win` is still unchanged and remembers the old value.)
https://github.com/MunifTanjim/nui.nvim/blob/c3c7fd618dcb5a89e443a2e1033e7d11fdb0596b/lua/nui/layout/utils.lua#L145
- Pass `win_config` instead of `internal.position` to `mod.get_container_info` here.
https://github.com/MunifTanjim/nui.nvim/blob/c3c7fd618dcb5a89e443a2e1033e7d11fdb0596b/lua/nui/layout/utils.lua#L156
Basically we need to pass a table with `win = nil` to `get_window_size()` that is called inside `get_container_info`, or deal with invalid …

fix(popup): always use current window when position == "cursor"

---

lua/nui/popup/border.lua

for previous behavior:
```lua
border = {
style = { "▛", "▀", "▜", "▐", "▟", "▄", "▙", "▌" },
},
```
---
resolves #351

fix(popup): mimic native 'solid' border

---

lua/nui/layout/utils.lua

ref: https://github.com/kawre/leetcode.nvim/issues/95
`mod.get_container_info` is missing winid if container is relative to editor

fix(input): add missing `winid`

---

lua/nui/utils/init.lua
tests/helpers/init.lua

`vim.tbl_islist` was deprecated in 0.10, and will be removed in 0.12.

refactor: avoid using the deprecated `vim.tbl_islist`

---

lua/nui/layout/float.lua
tests/nui/layout/init_spec.lua

fix(layout): handle if child.grow results in height <= 0

---

lua/nui/input/README.md

variable name changed from 'split' to 'input'

chore: fix variable misstype in input/README.md

---

lua/nui/tree/init.lua

This is really small change, but I was blind enough and spend hours of debugging because I could not find the node with "idXY" :).

fix: adjust error message text for duplicate node

---

lua/nui/popup/border.lua

On neovim v0.11, there's a `'winborder'` option which dictates what the default border of a floating window should be. This breaks nui popups (such as NuiInput) w/ non-simple borders since they open 2 windows - one for the inner window, and one for the border, and both windows would show borders if `winborder ~= 'none'|''` (instead of the expected behavior where only the border window has the border)
To resolve this, the inner window should explicitly resolve to its border to "none" instead of nil when a complex border is used.

fix(popup): explicitly remove inner border when border is complex
