MunifTanjim/nui.nvim

README.md

Most useful PR ever (assuming the README is incorrect and the code intends it to be this way).

fix: Opacity value notes in README.

---

README.md
lua/nui/menu.lua

**Example**:
```lua
local Menu = require("nui.menu")
local menu = Menu({
relative = "cursor",
border = {
style = "rounded",
highlight = "Normal",
text = {
top = "[Sample Menu]",
top_align = "left",
},
},
position = {
row = 1,
col = 0,
},
highlight = "Normal:Normal",
}, {
lines = {
Menu.separator("Group One"),
Menu.item("Item 1"),
Menu.item("Item 2"),
Menu.item("Item 3"),
Menu.separator("Group Two"),
Menu.item("Very Very Long Item 4"),
Menu.item("Item 5"),
Menu.item("Item 6"),
},
max_width = 20,
max_height = 4,
separator = {
char = "-",
text_align = "right",
},
keymap = {
focus_next = { "j", "<Down>", "<Tab>" },
focus_prev = { "k", "<Up>", "<S-Tab>" },
close = { "<Esc>", "<C-c>" },
submit = { "<CR>", "<Space>" },
},
on_close = function()
print("CLOSED")
end,
on_submit = function(item) …
```

Menu Component

---

README.md
lua/nui/popup/init.lua
lua/nui/split/init.lua
lua/nui/utils/init.lua

**Example**:
```lua
local Split = require("nui.split")
local split = Split({
relative = "editor",
position = "bottom",
size = "20%",
})
split:mount()
-- -- hide split
-- split:hide()
-- -- show split
-- split:show()
split:unmount()
```

Split Component

---

lua/nui/popup/border.lua

fix(border): pass copy of border style table

---

README.md
lua/nui/input/README.md
lua/nui/menu/README.md
lua/nui/popup/README.md
lua/nui/split/README.md

---
I've cleaned up the docs for the popup. I left a few TODOs where I didn't know what to put so please let me know what goes there.
Before I do the remaining components, I'd like your input. 
I'm open to suggestions in regards to formatting and arranging everything so please provide feedback if you have any.
[HERE](https://github.com/vuki656/nui.nvim) is how the home page `.md` looks like and [HERE](https://github.com/vuki656/nui.nvim/blob/main/doc/components/popup.md) is the full popup API
Closes #7

Revamp Documentation

---

README.md
lua/nui/tree/README.md
lua/nui/tree/init.lua
lua/nui/utils/init.lua

**Example**:
```lua
local NuiTree = require("nui.tree")
local Split = require("nui.split")
local split = Split({
relative = "win",
position = "bottom",
size = 30,
})
split:mount()
-- quit
split:map("n", "q", function()
split:unmount()
end, { noremap = true })
local tree = NuiTree({
winid = split.winid,
nodes = {
NuiTree.Node({ text = "a" }),
NuiTree.Node({ text = "b" }, {
NuiTree.Node({ text = "b-1" }),
NuiTree.Node({ text = "b-2" }, {
NuiTree.Node({ text = "b-1-a" }),
NuiTree.Node({ text = "b-2-b" }),
}),
}),
NuiTree.Node({ text = "c" }, {
NuiTree.Node({ text = "c-1" }),
NuiTree.Node({ text = "c-2" }),
}),
},
prepare_node = function(node)
local line = NuiLine()
line:append(string.rep("  ", node:get_depth() - 1))
if node:has_children() then
line:append(node:is_expanded() and " " or " ", …
```

Add NuiTree

---

.github/workflows/ci.yml
scripts/test.sh
tests/minimal_init.vim
tests/nui/init_spec.lua

Setup Automated Tests

---

lua/nui/text/README.md
lua/nui/text/init.lua
lua/nui/utils/init.lua
lua/tests/nui/init.lua
tests/nui/line/init_spec.lua
tests/nui/text/init_spec.lua

- Support cloning existing NuiText object
- Use extmarks for highlighting (opens up possibility for other related things)

Enhance NuiText

---

lua/nui/menu/README.md
lua/nui/menu/init.lua
lua/tests/nui/init.lua
tests/nui/menu/init_spec.lua

feat(menu): support options.on_change

---

lua/nui/menu/README.md
lua/nui/menu/init.lua
tests/nui/menu/init_spec.lua

Support NuiText for Menu.item and Menu.separator

---

lua/nui/tree/README.md
lua/nui/tree/init.lua
tests/nui/tree/init_spec.lua

https://github.com/MunifTanjim/nui.nvim/discussions/71

feat(tree): add method tree:set_nodes(nodes, parent_id?)

---

lua/nui/tree/README.md
lua/nui/tree/init.lua
lua/nui/tree/util.lua
tests/nui/tree/init_spec.lua

Related Issues:
- https://github.com/MunifTanjim/nui.nvim/issues/70
- https://github.com/MunifTanjim/nui.nvim/issues/73

NuiTree enhancements

---

lua/nui/popup/README.md
lua/nui/popup/init.lua
lua/nui/utils/keymap.lua
tests/nui/popup/init_spec.lua

Support unmanaged buffer for Popup

---

lua/nui/input/init.lua
lua/nui/line/init.lua
lua/nui/menu/init.lua
lua/nui/popup/border.lua
lua/nui/popup/init.lua
lua/nui/split/init.lua
lua/nui/text/init.lua
lua/nui/tree/init.lua
scripts/test.sh
tests/nui/tree/init_spec.lua

- No new behavior is introduced. 
- No documented behavior is changed.
- Anything documented in the `*/README.md` files will keep working as expected.
- If [Lua Language Server](https://github.com/sumneko/lua-language-server) is properly set up, it will provide completion and documentation.

Refactor and Improve Developer Experience

---

lua/nui/popup/init.lua
lua/nui/split/init.lua
tests/nui/popup/init_spec.lua
tests/nui/split/init_spec.lua

Allow :map, :unmap, :on, :off before :mount

---

lua/nui/text/init.lua
lua/tests/nui/init.lua
tests/nui/input/init_spec.lua
tests/nui/line/init_spec.lua
tests/nui/menu/init_spec.lua
tests/nui/popup/border_spec.lua
tests/nui/text/init_spec.lua

Reverts #150 
Reverts #151 
Resolves #152

Revert #150 #151

---

lua/nui/line/README.md
lua/nui/line/init.lua
lua/nui/menu/README.md
lua/nui/menu/init.lua
lua/nui/utils/init.lua
tests/nui/line/init_spec.lua
tests/nui/menu/init_spec.lua

feat(menu): support nui.line for Menu.item

---

lua/nui/object/init.lua
tests/nui/object/init_spec.lua

- `is_instance(instance, class)`
- `instance:is_instance_of(class)`
- `is_subclass(subclass, class)`
- `subclass:is_subclass_of(class)`

feat(object): add helper functions

---

lua/nui/popup/border.lua
lua/nui/popup/init.lua
lua/nui/split/README.md
lua/nui/split/init.lua
lua/nui/tree/init.lua
lua/nui/utils/init.lua

feat: clear namespace

---

lua/nui/layout/init.lua
lua/nui/layout/split.lua
lua/nui/split/utils.lua
lua/nui/utils/init.lua
tests/helpers/init.lua
tests/nui/layout/init_spec.lua

https://github.com/MunifTanjim/nui.nvim/issues/163

feat(layout): support split component box

---

lua/nui/split/init.lua

fix(split): skip manual buf/win removal when pending quit

---

lua/nui/popup/init.lua
tests/nui/popup/init_spec.lua

fix(popup): ignore WinClosed from other popup

---

lua/nui/popup/init.lua
lua/nui/utils/autocmd.lua
tests/nui/popup/init_spec.lua

fix(popup): do BufWinEnter autocmd after self.winid is set

---

lua/nui/popup/init.lua

Fix for changes introduced in https://github.com/MunifTanjim/nui.nvim/pull/192.
For some reason tests passed in that PR, but now they're failing.

fix(popup): manual doautocmd BufWinEnter

---

README.md

https://github.com/badges/shields/issues/8671

docs: fix badge for ci status

---

lua/nui/popup/border.lua

fixes https://github.com/MunifTanjim/nui.nvim/issues/218

fix(popup): border padding with style=shadow

---

lua/nui/layout/float.lua
lua/nui/layout/init.lua
lua/nui/layout/split.lua
lua/nui/split/init.lua
tests/nui/layout/init_spec.lua

fixes https://github.com/MunifTanjim/nui.nvim/issues/221

fix(layout): process layout box change

---

lua/nui/tree/init.lua
tests/nui/tree/init_spec.lua

Note, I can't get the unit tests to run, this may not work as intended. Additionally, waiting for response on what to do with the child nodes on removal, right now they are tossed into the ether, that may not be ideal. Still, I think this accomplishes what is being asked in #227

Added basic child removal on remove_node

---

lua/nui/layout/float.lua
tests/nui/layout/init_spec.lua

Related PR:
- https://github.com/MunifTanjim/nui.nvim/pull/204
Fixes: https://github.com/MunifTanjim/nui.nvim/issues/230

fix(layout): float position calculation for child with complex border

---

lua/nui/layout/init.lua
lua/nui/popup/init.lua
lua/nui/split/init.lua
tests/nui/layout/init_spec.lua
tests/nui/popup/init_spec.lua
tests/nui/split/init_spec.lua

so that callback attached by consumer gets the chance to run first
resolves https://github.com/MunifTanjim/nui.nvim/issues/236

fix: vim.schedule QuitPre event callback

---

.github/workflows/ci.yml

ci: introduce automated release

---

lua/nui/layout/init.lua
lua/nui/layout/split.lua
lua/nui/split/init.lua
lua/nui/split/utils.lua
tests/nui/split/init_spec.lua

- https://github.com/MunifTanjim/nui.nvim/issues/253

feat(layout): improve split size calculation

---

lua/nui/layout/init.lua

- https://github.com/MunifTanjim/nui.nvim/issues/253

fix(layout): focus on relative.win for split ':update'

---

README.md
lua/nui/line/init.lua
lua/nui/table/README.md
lua/nui/table/init.lua
lua/nui/utils/init.lua
tests/nui/table/init_spec.lua

The API is inspired by [TanStack Table](https://tanstack.com/table).
```lua
local Line = require("nui.line")
local Split = require("nui.split")
local Table = require("nui.table")
local Text = require("nui.text")
local split = Split({
position = "bottom",
size = 20,
})
local function cell_id(cell)
return cell.column.id
end
local function capitalize(value)
return (string.gsub(value, "^%l", string.upper))
end
local grouped_columns = {
{
align = "center",
header = "Name",
footer = cell_id,
columns = {
{
accessor_key = "firstName",
cell = function(cell)
return Text(capitalize(cell.get_value()), "DiagnosticInfo")
end,
header = "First",
footer = cell_id,
},
{
id = "lastName",
accessor_fn = function(row)
return capitalize(row.lastName)
end,
header = "Last",
footer = cell_id,
},
},
},
{
align = …
```

feat(table): add nui.table block

---

lua/nui/popup/border.lua
tests/nui/popup/border_spec.lua

resolves https://github.com/MunifTanjim/nui.nvim/issues/270

fix(popup): ensure valid border.bufnr on mount

---

lua/nui/layout/init.lua
tests/nui/layout/init_spec.lua

ref: https://github.com/neovim/neovim/issues/18925

fix(layout): more robust workaround for neovim/neovim#18925

---

lua/nui/tree/init.lua
tests/nui/tree/init_spec.lua

feat(tree): allow node:expand with zero child

---

lua/nui/layout/README.md

docs(layout): add docs for split layout and box nesting

---

lua/nui/input/init.lua
tests/nui/input/init_spec.lua

fix(input): check mounted state in mount/unmount method

---

lua/nui/popup/border.lua
lua/nui/utils/init.lua

feat(utils): replace deprecated api to set option

---

lua/nui/popup/border.lua
tests/nui/popup/border_spec.lua

fix(popup): use popup winblend for border

---

lua/nui/popup/border.lua
tests/nui/popup/border_spec.lua

resolves https://github.com/MunifTanjim/nui.nvim/issues/311

fix(popup): support border:set_text before layout mount

---

lua/nui/input/init.lua

fix(input): skip cursor position patch for hidden input

---

lua/nui/layout/float.lua
tests/nui/layout/init_spec.lua

fix(layout): starting current position for nested boxes

---

lua/nui/table/README.md
lua/nui/table/init.lua
tests/nui/table/init_spec.lua

Resolves https://github.com/MunifTanjim/nui.nvim/issues/342

feat(table): accept param 'position' for method 'get_cell' and expose NuiTable.Cell.range

---

lua/nui/input/init.lua

Related PRs:
- https://github.com/MunifTanjim/nui.nvim/pull/258

fix(input): ignore 'keymap' for feeding default value

---

lua/nui/layout/init.lua
lua/nui/popup/init.lua
lua/nui/split/init.lua

- NuiLayout
- NuiPopup
- NuiInput
Ref https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1211

fix(layout): set nested option for autocmds with self:hide

---

lua/nui/input/init.lua
lua/nui/layout/utils.lua
tests/nui/layout/utils_spec.lua

fix(input): cursor position patch w/ relative=cursor

---

lua/nui/layout/init.lua
scripts/test.sh

fix(layout): immediate hide/unmount after mounting

---

lua/nui/input/init.lua

resolves https://github.com/MunifTanjim/nui.nvim/issues/368

fix(input): mounting multiple inputs together

---

lua/nui/popup/border.lua

feat(popup): use same zindex for border

---

lua/nui/utils/init.lua
tests/nui/menu/init_spec.lua

support truncating Chinese characters based on the maximum width.

feat: update nui/utils/init.lua, support truncating Chinese characters based on the maximum width.
